# Generated by Django 4.0.2 on 2022-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=12, null=True)),
                ('sensor_type', models.CharField(max_length=22, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
