# Generated by Django 4.0.2 on 2022-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
